version: '3.8'

services:
  backend:
    image: aswinhariram/portfolio-backend:latest
    ports:
      - "8001:8001"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: aswinhariram/portfolio-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  portfolio-network:
    driver: bridge

volumes:
  backend_data:
