version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - aswinhariram/portfolio-frontend:latest
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - aswinhariram/portfolio-backend:latest
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PORT=5001

networks:
  default:
    name: portfolio-network
    driver: bridge
