name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      VITE_CONTACT_URL: ${{ secrets.VITE_CONTACT_URL || 'http://localhost:8001/contact' }}
      VITE_RESUME_URL: ${{ secrets.VITE_RESUME_URL || 'https://drive.google.com/file/d/15oiB_aswF5fdKCB2Db7Yu6pJE54bBHXM/view?usp=sharing' }}
      VITE_CHAT_API_URL: ${{ secrets.VITE_CHAT_API_URL || 'http://localhost:8001/chat' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/portfolio-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/portfolio-frontend:latest
          build-args: |
            VITE_Contact_URL=${{ env.VITE_CONTACT_URL }}
            VITE_RESUME_URL=${{ env.VITE_RESUME_URL }}
            VITE_CHAT_API_URL=${{ env.VITE_CHAT_API_URL }}
